server:
  port: 8004

spring:
  application:
    name: microServiceCloudProviderDeptHystrix

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: spring-cloud-provider-8004
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app.name: micro-service-cloud-provider-dept-hystrix
  company.name: com.wenq
  build.artifactId: @project.artifactId@
  build.version: @project.version@